# Generated by Django 2.1.1 on 2018-09-22 12:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('avatar_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='pig', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='AvatarPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_name', models.CharField(default=None, max_length=80)),
                ('avatar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Avatar')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(default='50,100,50', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('map', models.IntegerField(default=1)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='avatarplayer',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='avatarplayer',
            unique_together={('avatar_id', 'player_id')},
        ),
    ]
