# Generated by Django 2.1.1 on 2018-09-22 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(default='', max_length=65535)),
                ('timestamp', models.BigIntegerField(default=0)),
                ('player_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Player')),
            ],
        ),
    ]
