# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.CharField(default='', max_length=65536),
        ),
    ]
