# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id_avatar', models.AutoField(primary_key=True, serialize=False)),
                ('avatar_name', models.CharField(max_length=50)),
                ('sex', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AvatarStyle',
            fields=[
                ('id_style', models.AutoField(primary_key=True, serialize=False)),
                ('hair', models.IntegerField()),
                ('hair_color', models.IntegerField()),
                ('eyes', models.IntegerField()),
                ('skin_color', models.IntegerField()),
                ('id_avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Avatar')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id_player', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='avatar',
            name='id_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Player'),
        ),
    ]
