# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='user', max_length=80)),
                ('chat_permission_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ChatPermission')),
            ],
        ),
    ]
