# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='user', max_length=80)),
                ('strength', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ChatPermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Role')),
            ],
        ),
    ]
