# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170309_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='strength',
            field=models.IntegerField(default=1),
        ),
    ]
